services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-https://airox.ai}
        NEXT_TELEMETRY_DISABLED: 1
      # Build optimizations
      cache_from:
        - node:20-alpine
      target: runner
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3013}:3000"
    env_file:
      - .env.deploy
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    # Resource limits for better performance
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
      cache_from:
        - node:20-alpine
    restart: unless-stopped
    env_file:
      - .env.deploy
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_APP_URL=http://app:3000
    depends_on:
      app:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  db:
    container_name: airox-db
    image: postgres:16.4-alpine
    restart: unless-stopped
    volumes:
      - postgres_data_airox_app:/var/lib/postgresql/data
    env_file:
      - .env.deploy
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_EXTERNAL_PORT:-5433}:5432"
    networks:
      app-network:
        aliases:
          - airox-db-internal
    # Health check for faster startup
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DATABASE_USER:-postgres} -d ${DATABASE_NAME:-airox}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  app-network:
    external:
      name: global-shared

volumes:
  postgres_data_airox_app:
